name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: chemin/vers/votre/projet

    - name: Run tests
      run: npm test
      working-directory: chemin/vers/votre/projet

    - name: Run ESLint
      run: npm run lint
      working-directory: chemin/vers/votre/projet
